# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41f807a748e733ddc07dc5321f2cd6e9a5ad2f22fb1635ef5230f1c10c9c9508264c3e57cd7ae08e133f81d690ef407342b15b2634f086ae551f757ccf8796b5

test:
  secret_key_base: 722b559d303ed039956c95dac95dc87788b7163cbd5b69b5f45fdca0ea94d4bf218f0009c2e24855933034104379e43d3ce6698102c6bdaae028a158b4bc4660

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
